language: python
dist: xenial
sudo: yes
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"
script:
  - nosetests
notifications:
  irc:
    channels: "irc.freenode.org#pyrat"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change
